// ============================================================
//  AUTO-GENERATED FILE -- DO NOT EDIT BY HAND
//  Regenerated by scripts/stamp-version.ps1 (runs before each commit
//  via the .git/hooks/pre-commit hook). Edit the VERSION file to
//  change the semantic version number.
// ============================================================
window.BUILD_INFO = {
  version: "1.0.1",
  commit:  "50d8a69",
  date:    "2026-07-01 08:22:54"
};