// ============================================================
//  AUTO-GENERATED FILE -- DO NOT EDIT BY HAND
//  Regenerated by scripts/stamp-version.ps1 (runs before each commit
//  via the .git/hooks/pre-commit hook). Edit the VERSION file to
//  change the semantic version number.
// ============================================================
window.BUILD_INFO = {
  version: "1.0.0",
  commit:  "2d6a9fd",
  date:    "2026-07-01 19:06:15"
};